"""add_flavors_nic_bases

Revision ID: a935165242d4
Revises: d03b36bb1e41
Create Date: 2026-03-05 22:08:58.603593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a935165242d4'
down_revision: Union[str, None] = 'd03b36bb1e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_pg', sa.Float(), nullable=False),
    sa.Column('base_vg', sa.Float(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('cost_per_ml', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_custom', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nic_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strength_mg', sa.Float(), nullable=False),
    sa.Column('base_pg', sa.Float(), nullable=False),
    sa.Column('base_vg', sa.Float(), nullable=False),
    sa.Column('cost_per_ml', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_flavors', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_recipe_flavors_flavor_id', 'flavors', ['flavor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_flavors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipe_flavors_flavor_id', type_='foreignkey')

    op.drop_table('nic_bases')
    op.drop_table('flavors')
    # ### end Alembic commands ###
