"""initial_recipes

Revision ID: d03b36bb1e41
Revises: 
Create Date: 2026-03-05 21:54:35.274307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd03b36bb1e41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch_size_ml', sa.Float(), nullable=False),
    sa.Column('target_nic_mg', sa.Float(), nullable=False),
    sa.Column('nic_base_strength_mg', sa.Float(), nullable=False),
    sa.Column('nic_base_pg', sa.Float(), nullable=False),
    sa.Column('nic_base_vg', sa.Float(), nullable=False),
    sa.Column('nic_base_density', sa.Float(), nullable=False),
    sa.Column('nic_cost_per_ml', sa.Float(), nullable=False),
    sa.Column('pg_ratio', sa.Float(), nullable=False),
    sa.Column('vg_ratio', sa.Float(), nullable=False),
    sa.Column('pg_cost_per_ml', sa.Float(), nullable=False),
    sa.Column('vg_cost_per_ml', sa.Float(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_flavors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('flavor_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('pg_ratio', sa.Float(), nullable=False),
    sa.Column('vg_ratio', sa.Float(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('cost_per_ml', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_flavors')
    op.drop_table('recipes')
    # ### end Alembic commands ###
